In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split  
from sklearn.metrics import confusion_matrix, classification_report
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [3]:
df = pd.read_csv("Data-Collisions (1).csv")

df = df.iloc[:, [0, 15, 16, 19,22, 27, 28, 29]]
print(df)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


        SEVERITYCODE COLLISIONTYPE  PERSONCOUNT  VEHCOUNT  \
0                  2        Angles            2         2   
1                  1     Sideswipe            2         2   
2                  1    Parked Car            4         3   
3                  1         Other            3         3   
4                  2        Angles            2         2   
...              ...           ...          ...       ...   
194668             2       Head On            3         2   
194669             1    Rear Ended            2         2   
194670             2     Left Turn            3         2   
194671             2        Cycles            2         1   
194672             1    Rear Ended            2         2   

                                   JUNCTIONTYPE   WEATHER ROADCOND  \
0        At Intersection (intersection related)  Overcast      Wet   
1       Mid-Block (not related to intersection)   Raining      Wet   
2       Mid-Block (not related to intersection)  Overcast

In [4]:
print(df.isnull().sum())
df["WEATHER"] = df["WEATHER"].astype('category')
df["WEATHER"] = df["WEATHER"].cat.codes
df['COLLISIONTYPE'] = df['COLLISIONTYPE'].astype('category')
df['COLLISIONTYPE'] = df['COLLISIONTYPE'].cat.codes
df['JUNCTIONTYPE'] = df['JUNCTIONTYPE'].astype('category')
df['JUNCTIONTYPE'] = df['JUNCTIONTYPE'].cat.codes
df['ROADCOND'] = df['ROADCOND'].astype('category')
df['ROADCOND'] = df['ROADCOND'].cat.codes
df['LIGHTCOND'] = df['LIGHTCOND'].astype('category')
df['LIGHTCOND'] = df['LIGHTCOND'].cat.codes
df.head()

SEVERITYCODE        0
COLLISIONTYPE    4904
PERSONCOUNT         0
VEHCOUNT            0
JUNCTIONTYPE     6329
WEATHER          5081
ROADCOND         5012
LIGHTCOND        5170
dtype: int64


SEVERITYCODE  COLLISIONTYPE  PERSONCOUNT  VEHCOUNT  JUNCTIONTYPE  WEATHER  \
0             2              0            2         2             1        4   
1             1              9            2         2             4        6   
2             1              5            4         3             4        4   
3             1              4            3         3             4        1   
4             2              0            2         2             1        6   

   ROADCOND  LIGHTCOND  
0         8          5  
1         8          2  
2         0          5  
3         0          5  
4         8          5

In [5]:
target_column = ['SEVERITYCODE'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min       25%       50%  \
SEVERITYCODE   194673.0  1.298901  0.457778  1.000000  1.000000  1.000000   
COLLISIONTYPE  194673.0  0.485042  0.320098 -0.111111  0.333333  0.555556   
PERSONCOUNT    194673.0  0.030178  0.016616  0.000000  0.024691  0.024691   
VEHCOUNT       194673.0  0.160065  0.052587  0.000000  0.166667  0.166667   
JUNCTIONTYPE   194673.0  0.433442  0.251009 -0.166667  0.166667  0.500000   
WEATHER        194673.0  0.297725  0.289201 -0.100000  0.100000  0.100000   
ROADCOND       194673.0  0.313390  0.456083 -0.125000  0.000000  0.000000   
LIGHTCOND      194673.0  0.532052  0.237590 -0.125000  0.250000  0.625000   

                    75%  max  
SEVERITYCODE   2.000000  2.0  
COLLISIONTYPE  0.777778  1.0  
PERSONCOUNT    0.037037  1.0  
VEHCOUNT       0.166667  1.0  
JUNCTIONTYPE   0.666667  1.0  
WEATHER        0.600000  1.0  
ROADCOND       0.875000  1.0  
LIGHTCOND      0.625000  1.0

In [9]:
X = df[['COLLISIONTYPE', 'PERSONCOUNT', 'VEHCOUNT', 'JUNCTIONTYPE', 'WEATHER', 'ROADCOND', 'LIGHTCOND']].values
Y = df['SEVERITYCODE']

In [11]:
from sklearn.model_selection import train_test_split
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, Y, test_size=0.3, random_state=3)

In [12]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train.values.ravel())
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:587: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


[[90523  4993]
 [29541 11214]]


              precision    recall  f1-score   support

           1       0.75      0.95      0.84     95516
           2       0.69      0.28      0.39     40755

    accuracy                           0.75    136271
   macro avg       0.72      0.61      0.62    136271
weighted avg       0.74      0.75      0.71    136271



In [13]:
X = df[['COLLISIONTYPE', 'PERSONCOUNT', 'VEHCOUNT', 'JUNCTIONTYPE', 'WEATHER', 'ROADCOND', 'LIGHTCOND']].values
y = df['SEVERITYCODE']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(136271, 7)
(58402, 7)


In [7]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[89348  6168]
 [27315 13440]]


              precision    recall  f1-score   support

           1       0.77      0.94      0.84     95516
           2       0.69      0.33      0.45     40755

    accuracy                           0.75    136271
   macro avg       0.73      0.63      0.64    136271
weighted avg       0.74      0.75      0.72    136271



In [8]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[38272  2697]
 [11593  5840]]


              precision    recall  f1-score   support

           1       0.77      0.93      0.84     40969
           2       0.68      0.33      0.45     17433

    accuracy                           0.76     58402
   macro avg       0.73      0.63      0.65     58402
weighted avg       0.74      0.76      0.73     58402

